project_id = "dmwyqyqaseyuybqfawvk"

[functions.admin-delete-user]
verify_jwt = true

[functions.calculate-project-margins]
verify_jwt = true

[functions.check-margin-alerts]
verify_jwt = false

[functions.check-project-deadlines]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = true

[functions.send-budget-notification]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-events]
verify_jwt = true

[functions.public-timesheet]
verify_jwt = false

[functions.create-deleted-profile]
verify_jwt = true

[functions.fatture-in-cloud-oauth]
verify_jwt = false

[functions.fatture-in-cloud-register-webhook]
verify_jwt = false

[functions.fatture-in-cloud-webhook]
verify_jwt = false

[functions.google-drive-folders]
verify_jwt = false

[functions.project-completed-webhook]
verify_jwt = false

[functions.send-progress-reminder]
verify_jwt = false

[functions.send-slack-notification]
verify_jwt = false
