// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@2.109.0";
function anonKey() {
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY ?? "";
  if (!key) {
    throw new Error(
      "Missing Supabase anon key in the edge function environment (SUPABASE_PUBLISHABLE_KEY / SUPABASE_ANON_KEY)."
    );
  }
  return key;
}
function projectUrl() {
  const url = process.env.SUPABASE_URL ?? "";
  if (!url) throw new Error("Missing SUPABASE_URL in the edge function environment.");
  return url;
}
function supabaseForUser(ctx) {
  return createClient(projectUrl(), anonKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseAdmin() {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";
  if (!key) throw new Error("Missing SUPABASE_SERVICE_ROLE_KEY in the edge function environment.");
  return createClient(projectUrl(), key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
async function guarded(fn) {
  try {
    return await fn();
  } catch (e) {
    return errorResult(e instanceof Error ? e.message : String(e));
  }
}
async function resolveScope(ctx) {
  const meId = ctx.getUserId();
  const userClient = supabaseForUser(ctx);
  const [{ data: isAdmin }, { data: isTeamLeader }] = await Promise.all([
    userClient.rpc("has_role", { _user_id: meId, _role: "admin" }),
    userClient.rpc("has_role", { _user_id: meId, _role: "team_leader" })
  ]);
  if (isAdmin) return { scope: "admin", meId, allowedUserIds: null };
  if (isTeamLeader) {
    const admin = supabaseAdmin();
    const { data: areas, error: areasErr } = await admin.from("team_leader_areas").select("area").eq("user_id", meId);
    if (areasErr) throw new Error(areasErr.message);
    const areaList = (areas ?? []).map((a) => a.area);
    const ids = /* @__PURE__ */ new Set([meId]);
    if (areaList.length > 0) {
      const { data: profs, error: profErr } = await admin.from("profiles").select("id").in("area", areaList);
      if (profErr) throw new Error(profErr.message);
      for (const p of profs ?? []) ids.add(p.id);
    }
    return { scope: "team_leader", meId, allowedUserIds: ids };
  }
  return { scope: "self", meId, allowedUserIds: /* @__PURE__ */ new Set([meId]) };
}
async function searchUsers(query, allowedUserIds) {
  const admin = supabaseAdmin();
  let q = admin.from("profiles").select("id, first_name, last_name, email, area, approved").eq("approved", true).limit(500);
  if (allowedUserIds) q = q.in("id", Array.from(allowedUserIds));
  const { data, error } = await q;
  if (error) throw new Error(error.message);
  const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [];
  return (data ?? []).filter((p) => {
    const haystack = [p.first_name, p.last_name, p.email].filter(Boolean).join(" ").toLowerCase();
    return terms.every((t) => haystack.includes(t));
  }).map((p) => ({
    id: p.id,
    first_name: p.first_name,
    last_name: p.last_name,
    email: p.email,
    area: p.area
  }));
}

// src/lib/mcp/tools/list-projects.ts
function one(v) {
  if (Array.isArray(v)) return v[0] ?? null;
  return v ?? null;
}
function personName(p) {
  const r = one(p);
  if (!r) return null;
  const n = [r.first_name, r.last_name].filter(Boolean).join(" ").trim();
  return n || null;
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List projects visible to the signed-in user (RLS applied), with type, dates, budget, hours, progress, client, leader and billing metadata. Supports filtering by status, area, project type, client, name search and an activity date window.",
  inputSchema: {
    status: z.string().optional().describe("Filter by project_status (aperto, in_partenza, da_fatturare, completato)."),
    area: z.string().optional().describe("Filter by area (marketing, tech, branding, sales, ai, struttura, interno)."),
    project_type: z.string().optional().describe("Filter by project_type (e.g. pack, recurring, one_shot)."),
    client_id: z.string().uuid().optional().describe("Filter by client UUID."),
    search: z.string().optional().describe("Case-insensitive substring match on project name."),
    active_from: z.string().optional().describe("Only projects whose end_date is on/after this date (YYYY-MM-DD)."),
    active_to: z.string().optional().describe("Only projects whose start_date is on/before this date (YYYY-MM-DD)."),
    order_by: z.enum(["updated_at", "start_date", "end_date", "name"]).optional().describe("Sort field (default updated_at, descending)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, area, project_type, client_id, search, active_from, active_to, order_by, limit }, ctx) => guarded(async () => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const orderField = order_by ?? "updated_at";
    let query = supabase.from("projects").select(
      `id, name, project_type, project_status, area, discipline, progress,
           start_date, end_date, created_at, status_changed_at, updated_at,
           total_budget, total_hours, margin_percentage, discount_percentage,
           is_billable, billing_type, manual_quote_number,
           client_id, clients:client_id ( id, name ),
           client_contacts:client_contact_id ( id, first_name, last_name ),
           leader:project_leader_id ( id, first_name, last_name ),
           account:account_user_id ( id, first_name, last_name )`
    ).order(orderField, { ascending: orderField === "name" }).limit(limit ?? 50);
    if (status) query = query.eq("project_status", status);
    if (area) query = query.eq("area", area);
    if (project_type) query = query.eq("project_type", project_type);
    if (client_id) query = query.eq("client_id", client_id);
    if (search) query = query.ilike("name", `%${search}%`);
    if (active_from) query = query.or(`end_date.gte.${active_from},end_date.is.null`);
    if (active_to) query = query.or(`start_date.lte.${active_to},start_date.is.null`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    const projects = (data ?? []).map((p) => ({
      id: p.id,
      name: p.name,
      project_type: p.project_type,
      status: p.project_status,
      area: p.area,
      discipline: p.discipline,
      progress: p.progress,
      start_date: p.start_date,
      end_date: p.end_date,
      created_at: p.created_at,
      status_changed_at: p.status_changed_at,
      updated_at: p.updated_at,
      total_budget: p.total_budget,
      total_hours: p.total_hours,
      margin_percentage: p.margin_percentage,
      discount_percentage: p.discount_percentage,
      is_billable: p.is_billable,
      billing_type: p.billing_type,
      quote_number: p.manual_quote_number,
      client: one(p.clients),
      client_contact_name: personName(
        p.client_contacts
      ),
      project_leader_name: personName(
        p.leader
      ),
      account_name: personName(
        p.account
      )
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
      structuredContent: { projects, count: projects.length }
    };
  })
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.23.8";
function one2(v) {
  if (Array.isArray(v)) return v[0] ?? null;
  return v ?? null;
}
function name(p) {
  const r = one2(p);
  if (!r) return null;
  return [r.first_name, r.last_name].filter(Boolean).join(" ").trim() || null;
}
function round2(n) {
  return Math.round(n * 100) / 100;
}
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch a full project card by id (RLS applied): type, area, discipline, status, progress, dates, economics (budget, hours, discount, margin, additional costs), client and contact, leader/account, team members, planned activities, external links (Drive, Slack, quote number) and the latest progress updates.",
  inputSchema: {
    id: z2.string().uuid().describe("Project UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => guarded(async () => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: p, error } = await supabase.from("projects").select(
      `id, name, description, objective, secondary_objective, project_type, project_status,
           area, discipline, progress, start_date, end_date, created_at, updated_at, status_changed_at,
           total_budget, total_hours, discount_percentage, margin_percentage, manual_activities_budget,
           is_billable, billing_type, payment_terms, manual_quote_number, brief_link,
           drive_folder_id, drive_folder_name, slack_channel_id, slack_channel_name,
           client_id, clients:client_id ( id, name ),
           client_contacts:client_contact_id ( id, first_name, last_name, email ),
           leader:project_leader_id ( id, first_name, last_name ),
           account:account_user_id ( id, first_name, last_name ),
           assigned:assigned_user_id ( id, first_name, last_name )`
    ).eq("id", id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!p) return errorResult("Project not found or not accessible");
    const row = p;
    const [membersRes, itemsRes, costsRes, updatesRes, tasksRes] = await Promise.all([
      supabase.from("project_members").select("user_id, profiles:user_id ( first_name, last_name )").eq("project_id", id),
      supabase.from("budget_items").select("id, activity_name, category, hours_worked, hourly_rate, total_cost, assignee_name, is_product").eq("project_id", id).order("display_order", { ascending: true }),
      supabase.from("project_additional_costs").select("name, amount").eq("project_id", id),
      supabase.from("project_progress_updates").select("progress_value, update_text, roadblocks_text, created_at, user_id").eq("project_id", id).order("created_at", { ascending: false }).limit(5),
      supabase.from("project_tasks").select("id, status, due_date").eq("project_id", id)
    ]);
    for (const r of [membersRes, itemsRes, costsRes, updatesRes, tasksRes]) {
      if (r.error) return errorResult(r.error.message);
    }
    const items = itemsRes.data ?? [];
    const additionalCosts = costsRes.data ?? [];
    const tasks = tasksRes.data ?? [];
    const plannedHours = round2(items.reduce((s, i) => s + Number(i.hours_worked ?? 0), 0));
    const plannedCost = round2(items.reduce((s, i) => s + Number(i.total_cost ?? 0), 0));
    const additionalCostsTotal = round2(
      additionalCosts.reduce((s, c) => s + Number(c.amount ?? 0), 0)
    );
    const project = {
      identity: {
        id: row.id,
        name: row.name,
        description: row.description,
        objective: row.objective,
        secondary_objective: row.secondary_objective,
        project_type: row.project_type,
        area: row.area,
        discipline: row.discipline,
        status: row.project_status,
        progress: row.progress
      },
      dates: {
        start_date: row.start_date,
        end_date: row.end_date,
        created_at: row.created_at,
        updated_at: row.updated_at,
        status_changed_at: row.status_changed_at
      },
      economics: {
        total_budget: row.total_budget,
        total_hours: row.total_hours,
        planned_hours_from_activities: plannedHours,
        planned_cost_from_activities: plannedCost,
        manual_activities_budget: row.manual_activities_budget,
        discount_percentage: row.discount_percentage,
        margin_percentage: row.margin_percentage,
        additional_costs_total: additionalCostsTotal,
        additional_costs: additionalCosts,
        is_billable: row.is_billable,
        billing_type: row.billing_type,
        payment_terms: row.payment_terms
      },
      people: {
        client: one2(row.clients),
        client_contact: (() => {
          const c = one2(row.client_contacts);
          return c ? { id: c.id, name: name(c), email: c.email } : null;
        })(),
        project_leader: name(row.leader),
        account: name(row.account),
        assigned_user: name(row.assigned),
        members: (membersRes.data ?? []).map(
          (m) => ({ user_id: m.user_id, name: name(m.profiles) })
        )
      },
      activities: items.map((i) => ({
        id: i.id,
        activity_name: i.activity_name,
        category: i.category,
        planned_hours: i.hours_worked,
        hourly_rate: i.hourly_rate,
        total_cost: i.total_cost,
        assignee_name: i.assignee_name,
        is_product: i.is_product
      })),
      tasks_overview: {
        total: tasks.length,
        open: tasks.filter((t) => t.status !== "done" && t.status !== "completato").length,
        overdue: tasks.filter(
          (t) => t.due_date && t.status !== "done" && t.status !== "completato" && t.due_date < (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)
        ).length
      },
      links: {
        brief_link: row.brief_link,
        drive_folder_id: row.drive_folder_id,
        drive_folder_name: row.drive_folder_name,
        slack_channel_id: row.slack_channel_id,
        slack_channel_name: row.slack_channel_name,
        quote_number: row.manual_quote_number
      },
      recent_progress_updates: updatesRes.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(project, null, 2) }],
      structuredContent: { project }
    };
  })
});

// src/lib/mcp/tools/my-activities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.23.8";
var my_activities_default = defineTool3({
  name: "list_my_time_entries",
  title: "List my time entries",
  description: "List time-tracking entries recorded by the signed-in user, optionally within a date range. Uses RLS so only the caller's data is returned.",
  inputSchema: {
    from: z3.string().optional().describe("Inclusive start date (YYYY-MM-DD)."),
    to: z3.string().optional().describe("Inclusive end date (YYYY-MM-DD)."),
    limit: z3.number().int().min(1).max(500).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => guarded(async () => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("activity_time_tracking").select(
      "id, scheduled_date, actual_start_time, actual_end_time, notes, budget_item_id, user_id"
    ).eq("user_id", ctx.getUserId()).order("scheduled_date", { ascending: false }).limit(limit ?? 100);
    if (from) q = q.gte("scheduled_date", from);
    if (to) q = q.lte("scheduled_date", to);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  })
});

// src/lib/mcp/tools/list-time-entries.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.23.8";
function hoursBetween(start, end) {
  if (!start || !end) return 0;
  const ms = new Date(end).getTime() - new Date(start).getTime();
  if (!Number.isFinite(ms) || ms <= 0) return 0;
  return Math.round(ms / 36e5 * 100) / 100;
}
var list_time_entries_default = defineTool4({
  name: "list_time_entries",
  title: "List time entries",
  description: "List confirmed time-tracking entries. Pass user_id (UUID) or user_search (a person's name/email). Admins can query any user; team leaders are limited to users in their assigned areas; other roles are limited to their own entries. Only entries with actual_start_time and actual_end_time set are returned. Returns the entries plus an aggregated summary (total hours, hours per project).",
  inputSchema: {
    user_id: z4.string().uuid().optional().describe("Filter by user UUID. Requires admin, or team_leader access to that user's area."),
    user_search: z4.string().optional().describe(
      "Alternative to user_id: a name or email fragment. If several users match, the tool returns the candidates instead of entries."
    ),
    project_id: z4.string().uuid().optional().describe("Filter by project UUID."),
    from: z4.string().optional().describe("Inclusive start date (YYYY-MM-DD)."),
    to: z4.string().optional().describe("Inclusive end date (YYYY-MM-DD)."),
    limit: z4.number().int().min(1).max(500).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ user_id, user_search, project_id, from, to, limit }, ctx) => guarded(async () => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { scope, allowedUserIds } = await resolveScope(ctx);
    let targetUserId = user_id;
    let resolvedUser = null;
    if (!targetUserId && user_search) {
      const matches = await searchUsers(user_search, allowedUserIds);
      if (matches.length === 0) {
        return errorResult(
          `No approved user matches "${user_search}" within your allowed scope (${scope}).`
        );
      }
      if (matches.length > 1) {
        return {
          content: [
            {
              type: "text",
              text: `Multiple users match "${user_search}". Re-run with one of these user_id values:
${JSON.stringify(matches, null, 2)}`
            }
          ],
          structuredContent: { ambiguous: true, candidates: matches }
        };
      }
      targetUserId = matches[0].id;
      resolvedUser = matches[0];
    }
    if (targetUserId && allowedUserIds && !allowedUserIds.has(targetUserId)) {
      return errorResult("forbidden: user_id not in your allowed scope");
    }
    const admin = supabaseAdmin();
    let q = admin.from("activity_time_tracking").select(
      "id, scheduled_date, actual_start_time, actual_end_time, notes, user_id, budget_item_id, budget_items:budget_item_id ( project_id, activity_name, category, projects:project_id ( name ) )"
    ).not("actual_start_time", "is", null).not("actual_end_time", "is", null).order("scheduled_date", { ascending: false }).limit(limit ?? 100);
    if (targetUserId) {
      q = q.eq("user_id", targetUserId);
    } else if (allowedUserIds) {
      q = q.in("user_id", Array.from(allowedUserIds));
    }
    if (from) q = q.gte("scheduled_date", from);
    if (to) q = q.lte("scheduled_date", to);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    let rows = (data ?? []).map((r) => {
      const bi = Array.isArray(r.budget_items) ? r.budget_items[0] ?? null : r.budget_items;
      const proj = bi && (Array.isArray(bi.projects) ? bi.projects[0] ?? null : bi.projects);
      return { ...r, budget_items: bi, project_name: proj?.name ?? null };
    });
    if (project_id) {
      rows = rows.filter((r) => r.budget_items?.project_id === project_id);
    }
    const entries = rows.map((r) => ({
      id: r.id,
      user_id: r.user_id,
      project_id: r.budget_items?.project_id ?? null,
      project_name: r.project_name,
      budget_item_id: r.budget_item_id,
      activity_name: r.budget_items?.activity_name ?? null,
      category: r.budget_items?.category ?? null,
      scheduled_date: r.scheduled_date,
      actual_start_time: r.actual_start_time,
      actual_end_time: r.actual_end_time,
      hours: hoursBetween(r.actual_start_time, r.actual_end_time),
      notes: r.notes
    }));
    const byProject = /* @__PURE__ */ new Map();
    for (const e of entries) {
      const key = e.project_id ?? "unknown";
      const cur = byProject.get(key) ?? {
        project_id: e.project_id,
        project_name: e.project_name,
        hours: 0,
        entries: 0
      };
      cur.hours = Math.round((cur.hours + e.hours) * 100) / 100;
      cur.entries += 1;
      byProject.set(key, cur);
    }
    const summary = {
      scope,
      user_id: targetUserId ?? null,
      user_name: resolvedUser ? [resolvedUser.first_name, resolvedUser.last_name].filter(Boolean).join(" ") : null,
      from: from ?? null,
      to: to ?? null,
      entry_count: entries.length,
      total_hours: Math.round(entries.reduce((s, e) => s + e.hours, 0) * 100) / 100,
      truncated: entries.length >= (limit ?? 100),
      by_project: Array.from(byProject.values()).sort((a, b) => b.hours - a.hours)
    };
    return {
      content: [
        { type: "text", text: JSON.stringify({ summary, entries }, null, 2) }
      ],
      structuredContent: { summary, entries, scope }
    };
  })
});

// src/lib/mcp/tools/project-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.23.8";
function hoursBetween2(start, end) {
  if (!start || !end) return 0;
  const ms = new Date(end).getTime() - new Date(start).getTime();
  if (!Number.isFinite(ms) || ms <= 0) return 0;
  return ms / 36e5;
}
function round22(n) {
  return Math.round(n * 100) / 100;
}
var project_summary_default = defineTool5({
  name: "get_project_summary",
  title: "Get project summary",
  description: "Return a summary of a project (visible to the signed-in user via RLS): planned budget and hours, confirmed hours and cost from time tracking, plus additional costs. Numbers reflect only rows the caller is allowed to see.",
  inputSchema: {
    id: z5.string().uuid().describe("Project UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: project, error: projectErr } = await supabase.from("projects").select(
      "id, name, area, project_status, start_date, end_date, total_budget, total_hours, client_id, clients:client_id (id, name)"
    ).eq("id", id).maybeSingle();
    if (projectErr) {
      return { content: [{ type: "text", text: projectErr.message }], isError: true };
    }
    if (!project) {
      return {
        content: [{ type: "text", text: "Project not found or not accessible" }],
        isError: true
      };
    }
    const { data: items, error: itemsErr } = await supabase.from("budget_items").select("id, activity_name, category, hourly_rate, hours_worked, total_cost").eq("project_id", id);
    if (itemsErr) {
      return { content: [{ type: "text", text: itemsErr.message }], isError: true };
    }
    const budgetItems = items ?? [];
    const plannedHours = budgetItems.reduce((s, it) => s + Number(it.hours_worked ?? 0), 0);
    const plannedCost = budgetItems.reduce((s, it) => s + Number(it.total_cost ?? 0), 0);
    const rateById = new Map(
      budgetItems.map((it) => [it.id, Number(it.hourly_rate ?? 0)])
    );
    const itemIds = budgetItems.map((it) => it.id);
    const timeEntries = [];
    const idsBatchSize = 100;
    const pageSize = 1e3;
    for (let i = 0; i < itemIds.length; i += idsBatchSize) {
      const chunk = itemIds.slice(i, i + idsBatchSize);
      let offset = 0;
      while (true) {
        const { data: batch, error: ttErr } = await supabase.from("activity_time_tracking").select("budget_item_id, user_id, actual_start_time, actual_end_time").in("budget_item_id", chunk).not("actual_start_time", "is", null).not("actual_end_time", "is", null).order("id", { ascending: true }).range(offset, offset + pageSize - 1);
        if (ttErr) {
          return { content: [{ type: "text", text: ttErr.message }], isError: true };
        }
        const rows = batch ?? [];
        timeEntries.push(...rows);
        if (rows.length < pageSize) break;
        offset += pageSize;
      }
    }
    let confirmedHoursTotal = 0;
    let confirmedCostTotal = 0;
    let confirmedHoursMe = 0;
    let confirmedCostMe = 0;
    const meId = ctx.getUserId();
    for (const e of timeEntries) {
      const h = hoursBetween2(e.actual_start_time, e.actual_end_time);
      if (h === 0) continue;
      const rate = rateById.get(e.budget_item_id) ?? 0;
      const cost = h * rate;
      confirmedHoursTotal += h;
      confirmedCostTotal += cost;
      if (e.user_id === meId) {
        confirmedHoursMe += h;
        confirmedCostMe += cost;
      }
    }
    const { data: extraCosts, error: extraErr } = await supabase.from("project_additional_costs").select("amount").eq("project_id", id);
    if (extraErr) {
      return { content: [{ type: "text", text: extraErr.message }], isError: true };
    }
    const additionalCosts = (extraCosts ?? []).reduce(
      (s, c) => s + Number(c.amount ?? 0),
      0
    );
    const totalBudget = Number(project.total_budget ?? 0);
    const totalActualCost = confirmedCostTotal + additionalCosts;
    const residualBudget = totalBudget - totalActualCost;
    const budgetUsedPct = totalBudget > 0 ? totalActualCost / totalBudget * 100 : null;
    const hoursUsedPct = plannedHours > 0 ? confirmedHoursTotal / plannedHours * 100 : null;
    const summary = {
      project: {
        id: project.id,
        name: project.name,
        area: project.area,
        status: project.project_status,
        start_date: project.start_date,
        end_date: project.end_date,
        client: project.clients ?? null
      },
      planned: {
        total_budget: round22(totalBudget),
        total_hours: round22(plannedHours),
        total_cost: round22(plannedCost),
        activities_count: budgetItems.length
      },
      confirmed: {
        hours: round22(confirmedHoursTotal),
        cost: round22(confirmedCostTotal),
        entries_count: timeEntries.length
      },
      my_contribution: {
        hours: round22(confirmedHoursMe),
        cost: round22(confirmedCostMe)
      },
      additional_costs: round22(additionalCosts),
      totals: {
        total_actual_cost: round22(totalActualCost),
        residual_budget: round22(residualBudget),
        budget_used_pct: budgetUsedPct === null ? null : round22(budgetUsedPct),
        hours_used_pct: hoursUsedPct === null ? null : round22(hoursUsedPct)
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/find-users.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.23.8";
var find_users_default = defineTool6({
  name: "find_users",
  title: "Find users",
  description: "Search approved TimeTrap users by name or email and return their UUIDs. Use this first to resolve a person's name into a user_id before calling list_time_entries. Admins can search everyone; team leaders only users in their areas; other roles only themselves.",
  inputSchema: {
    query: z6.string().describe("Name, surname, full name or email fragment (case-insensitive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => guarded(async () => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { scope, allowedUserIds } = await resolveScope(ctx);
    const users = await searchUsers(query, allowedUserIds);
    return {
      content: [{ type: "text", text: JSON.stringify(users, null, 2) }],
      structuredContent: { users, scope, count: users.length }
    };
  })
});

// src/lib/mcp/index.ts
var projectRef = "dmwyqyqaseyuybqfawvk";
var mcp_default = defineMcp({
  name: "timetrap-mcp",
  title: "TimeTrap MCP",
  version: "0.1.0",
  instructions: "Tools for TimeTrap (Larin Budget Manager). To analyse a specific person's hours, first call find_users with their name to get their user_id, then call list_time_entries with that user_id (or pass user_search directly). Use list_projects to browse projects the signed-in user can see, get_project / get_project_summary for details, and list_my_time_entries for the caller's own timesheet.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated",
    // Also accept plain Supabase session tokens (no `client_id` claim) so the
    // API-key proxy function `mcp-key` can serve clients without OAuth support.
    requireOAuthClientClaim: false
  }),
  tools: [
    list_projects_default,
    get_project_default,
    my_activities_default,
    list_time_entries_default,
    project_summary_default,
    find_users_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
