// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.9";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List projects visible to the signed-in user (RLS applied). Supports filtering by status and free-text search on project name.",
  inputSchema: {
    status: z.string().optional().describe("Filter by project_status (e.g. approvato, in_corso, completato)."),
    search: z.string().optional().describe("Case-insensitive substring match on project name."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("id, name, project_status, area, start_date, end_date, client_id, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("project_status", status);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.9";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch a single project by id, with its client and basic metadata (RLS applied).",
  inputSchema: {
    id: z2.string().uuid().describe("Project UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("projects").select("*, clients:client_id (id, name)").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Project not found or not accessible" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/my-activities.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.9";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var my_activities_default = defineTool3({
  name: "list_my_time_entries",
  title: "List my time entries",
  description: "List time-tracking entries recorded by the signed-in user, optionally within a date range. Uses RLS so only the caller's data is returned.",
  inputSchema: {
    from: z3.string().optional().describe("Inclusive start date (YYYY-MM-DD)."),
    to: z3.string().optional().describe("Inclusive end date (YYYY-MM-DD)."),
    limit: z3.number().int().min(1).max(500).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("activity_time_tracking").select("id, scheduled_date, actual_start_time, actual_end_time, notes, budget_item_id, user_id").eq("user_id", ctx.getUserId()).order("scheduled_date", { ascending: false }).limit(limit ?? 100);
    if (from) q = q.gte("scheduled_date", from);
    if (to) q = q.lte("scheduled_date", to);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/project-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.9";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.23.8";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function hoursBetween(start, end) {
  if (!start || !end) return 0;
  const ms = new Date(end).getTime() - new Date(start).getTime();
  if (!Number.isFinite(ms) || ms <= 0) return 0;
  return ms / 36e5;
}
function round2(n) {
  return Math.round(n * 100) / 100;
}
var project_summary_default = defineTool4({
  name: "get_project_summary",
  title: "Get project summary",
  description: "Return a summary of a project (visible to the signed-in user via RLS): planned budget and hours, confirmed hours and cost from time tracking, plus additional costs. Numbers reflect only rows the caller is allowed to see.",
  inputSchema: {
    id: z4.string().uuid().describe("Project UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data: project, error: projectErr } = await supabase.from("projects").select(
      "id, name, area, project_status, start_date, end_date, total_budget, total_hours, client_id, clients:client_id (id, name)"
    ).eq("id", id).maybeSingle();
    if (projectErr) {
      return { content: [{ type: "text", text: projectErr.message }], isError: true };
    }
    if (!project) {
      return {
        content: [{ type: "text", text: "Project not found or not accessible" }],
        isError: true
      };
    }
    const { data: items, error: itemsErr } = await supabase.from("budget_items").select("id, activity_name, category, hourly_rate, hours_worked, total_cost").eq("project_id", id);
    if (itemsErr) {
      return { content: [{ type: "text", text: itemsErr.message }], isError: true };
    }
    const budgetItems = items ?? [];
    const plannedHours = budgetItems.reduce((s, it) => s + Number(it.hours_worked ?? 0), 0);
    const plannedCost = budgetItems.reduce((s, it) => s + Number(it.total_cost ?? 0), 0);
    const rateById = new Map(
      budgetItems.map((it) => [it.id, Number(it.hourly_rate ?? 0)])
    );
    const itemIds = budgetItems.map((it) => it.id);
    const timeEntries = [];
    const idsBatchSize = 100;
    const pageSize = 1e3;
    for (let i = 0; i < itemIds.length; i += idsBatchSize) {
      const chunk = itemIds.slice(i, i + idsBatchSize);
      let offset = 0;
      while (true) {
        const { data: batch, error: ttErr } = await supabase.from("activity_time_tracking").select("budget_item_id, user_id, actual_start_time, actual_end_time").in("budget_item_id", chunk).not("actual_start_time", "is", null).not("actual_end_time", "is", null).order("id", { ascending: true }).range(offset, offset + pageSize - 1);
        if (ttErr) {
          return { content: [{ type: "text", text: ttErr.message }], isError: true };
        }
        const rows = batch ?? [];
        timeEntries.push(...rows);
        if (rows.length < pageSize) break;
        offset += pageSize;
      }
    }
    let confirmedHoursTotal = 0;
    let confirmedCostTotal = 0;
    let confirmedHoursMe = 0;
    let confirmedCostMe = 0;
    const meId = ctx.getUserId();
    for (const e of timeEntries) {
      const h = hoursBetween(e.actual_start_time, e.actual_end_time);
      if (h === 0) continue;
      const rate = rateById.get(e.budget_item_id) ?? 0;
      const cost = h * rate;
      confirmedHoursTotal += h;
      confirmedCostTotal += cost;
      if (e.user_id === meId) {
        confirmedHoursMe += h;
        confirmedCostMe += cost;
      }
    }
    const { data: extraCosts, error: extraErr } = await supabase.from("project_additional_costs").select("amount").eq("project_id", id);
    if (extraErr) {
      return { content: [{ type: "text", text: extraErr.message }], isError: true };
    }
    const additionalCosts = (extraCosts ?? []).reduce(
      (s, c) => s + Number(c.amount ?? 0),
      0
    );
    const totalBudget = Number(project.total_budget ?? 0);
    const totalActualCost = confirmedCostTotal + additionalCosts;
    const residualBudget = totalBudget - totalActualCost;
    const budgetUsedPct = totalBudget > 0 ? totalActualCost / totalBudget * 100 : null;
    const hoursUsedPct = plannedHours > 0 ? confirmedHoursTotal / plannedHours * 100 : null;
    const summary = {
      project: {
        id: project.id,
        name: project.name,
        area: project.area,
        status: project.project_status,
        start_date: project.start_date,
        end_date: project.end_date,
        client: project.clients ?? null
      },
      planned: {
        total_budget: round2(totalBudget),
        total_hours: round2(plannedHours),
        total_cost: round2(plannedCost),
        activities_count: budgetItems.length
      },
      confirmed: {
        hours: round2(confirmedHoursTotal),
        cost: round2(confirmedCostTotal),
        entries_count: timeEntries.length
      },
      my_contribution: {
        hours: round2(confirmedHoursMe),
        cost: round2(confirmedCostMe)
      },
      additional_costs: round2(additionalCosts),
      totals: {
        total_actual_cost: round2(totalActualCost),
        residual_budget: round2(residualBudget),
        budget_used_pct: budgetUsedPct === null ? null : round2(budgetUsedPct),
        hours_used_pct: hoursUsedPct === null ? null : round2(hoursUsedPct)
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dmwyqyqaseyuybqfawvk";
var mcp_default = defineMcp({
  name: "timetrap-mcp",
  title: "TimeTrap MCP",
  version: "0.1.0",
  instructions: "Tools for TimeTrap (Larin Budget Manager). Use list_projects to browse projects the signed-in user can see, get_project for details, and list_my_time_entries to inspect the caller's own timesheet entries.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, get_project_default, my_activities_default, project_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
