INSERT INTO public.changelog (title, description, category, created_at) VALUES
('Schede Performance Personali','Nuova sezione Performance nel Profilo: scheda personale con punti di forza, aree di miglioramento, obiettivi annuali con bonus % e note trimestrali. Gestione admin in Impostazioni.','feature','2026-04-20 10:00:00+00'),
('Notifiche budget progressive','Alert automatici sul budget target a 50/75/90/100% di consumo, più warning di proiezione (>10%, >25%) per anticipare i rischi di sforamento.','improvement','2026-04-17 09:00:00+00'),
('Pagina Progetti Approvati','Nuova vista /approved-projects con monitor delle criticità (>85% budget consumato, <7gg dalla deadline, margine basso) e semaforo visivo.','feature','2026-04-15 11:00:00+00'),
('Filtro progetti aperti nel dialog Nuova attività','Il dialog per creare attività manuali mostra ora solo i progetti in stato Aperto di cui sei leader o membro.','bugfix','2026-04-10 14:00:00+00'),
('Banca Ore con previsionale','Nuova sezione Banca Ore nel Profilo: saldo annuale YTD, riporti, dettaglio mensile e previsionale a fine mese basato su pianificazione.','feature','2026-04-07 10:00:00+00'),
('Maggiorazioni Timesheet','Nel canvas progetto puoi applicare maggiorazioni % per utente o categoria, utili per straordinari e tariffe variabili.','feature','2026-03-31 09:00:00+00'),
('Workflows v2: dipendenze e commenti','I task dei flussi supportano dipendenze (dependsOn con lock a cascata), scadenze individuali e commenti contestuali.','feature','2026-03-30 10:00:00+00'),
('Ruolo External per collaboratori esterni','Nuovo ruolo External: accesso via magic link a progetti specifici, possibilità di assegnare attività solo a utenti consentiti.','feature','2026-03-24 11:00:00+00'),
('Ruolo Coordinator','Nuovo ruolo Coordinator con accesso in lettura a catalog (clienti, fornitori, prodotti) e budget; gestione template.','feature','2026-03-20 10:00:00+00'),
('Riepilogo settimanale AI','Ogni lunedì alle 09:00 ricevi via email un riepilogo intelligente di progetti attivi, criticità e ore lavorate.','improvement','2026-03-17 09:00:00+00'),
('Simulatore margine bidirezionale','Nei preventivi, simulatore di marginalità che permette di agire sul prezzo finale o sul margine target con calcolo bidirezionale.','feature','2026-03-10 10:00:00+00'),
('Aggregazione multi-budget nei preventivi','Un preventivo può aggregare più budget tramite la tabella ponte quote_budgets, utile per offerte composite.','feature','2026-03-05 10:00:00+00'),
('Promemoria pianificazione settimanale','Email automatica il venerdì per ricordare la pianificazione della settimana successiva.','improvement','2026-03-03 09:00:00+00'),
('Slack notifications','Notifiche su Slack per nuovo progetto, aggiornamenti progresso e completamento progetto, su canali dedicati.','feature','2026-02-28 10:00:00+00'),
('Integrazione Fatture in Cloud','OAuth con buffer 5min, gestione token unificata, invio preventivi e mappatura documenti automatica.','feature','2026-02-27 10:00:00+00'),
('Periodi contrattuali dinamici','Tabella user_contract_periods: ore attese e tariffe variano nel tempo per ciascun utente, override del profilo base.','feature','2026-02-20 10:00:00+00'),
('Project Leader unificato','Il Project Leader supersede i vincoli di membership: vede e modifica il progetto anche se non nel team.','improvement','2026-02-15 10:00:00+00'),
('Sync Google Sheet trattative','Sync automatico ogni 8h delle trattative draft da Foglio 3 verso budgets in stato in_attesa.','feature','2026-02-12 10:00:00+00'),
('Sync Google Sheet clienti','Sincronizzazione automatica ogni 6h di clienti e contatti da Google Sheet con mapping HubSpot Owner.','feature','2026-02-08 10:00:00+00'),
('Multi-company contacts','Un contatto può essere associato a più clienti tramite tabella di giunzione client_contact_clients.','improvement','2026-02-05 10:00:00+00'),
('Timeline export PDF A3','Esportazione timeline progetti in formato PDF A3 landscape con margini ottimizzati.','improvement','2026-02-01 10:00:00+00'),
('Progress tracking automatico','Per progetti recurring/pack la % di avanzamento viene calcolata automaticamente in base alle ricorrenze completate.','improvement','2026-01-28 10:00:00+00'),
('AI Insights personalizzati','Pannello insights generati on-demand con cache locale, suggerimenti specifici per ruolo (Admin, Team Leader, Account, Member).','feature','2026-01-22 10:00:00+00'),
('Timesheet pubblica con scadenza','Token con expiry e flag per nascondere dettagli finanziari nelle viste pubbliche timesheet.','improvement','2026-01-18 10:00:00+00'),
('Data chiusura attesa sui budget','Nuovo campo expected_close_date sui budget per simulazioni di pianificazione risorse what-if.','feature','2026-01-12 10:00:00+00'),
('Sicurezza: roles in tabella separata','User roles spostati in tabella user_roles con security definer, prevenzione attacchi privilege escalation.','improvement','2026-01-08 10:00:00+00');