INSERT INTO public.changelog (title, description, category, created_at) VALUES
('Progress drafts AI da Gmail', 'I draft settimanali di avanzamento progetto ora aggregano anche le email Gmail (impersonation domain-wide), oltre a Slack e trascrizioni Meet su Drive.', 'feature', '2026-04-23 10:00:00+02'),
('Diagnostica cron e invocazione manuale', 'In Impostazioni → System Monitor è ora possibile lanciare manualmente i cron job HTTP, vedere ultime esecuzioni, errori e stato (solo admin).', 'improvement', '2026-04-23 11:00:00+02'),
('Dialog AI draft negli aggiornamenti progresso', 'Quando crei un aggiornamento di progresso, un pulsante AI propone una bozza basata sulle attività della settimana — la puoi modificare prima di salvare.', 'feature', '2026-04-24 10:00:00+02'),
('Aggiornamento progresso aperto a più ruoli', 'Membri del team e Project Leader possono ora aggiornare il progresso dei progetti di cui fanno parte (prima riservato ad admin/team leader).', 'improvement', '2026-04-24 11:00:00+02'),
('Area sui flussi (workflows)', 'Ogni flusso può essere assegnato a un''area aziendale (Marketing, Tech, Branding, Sales, Jarvis, Struttura, Interno) per filtri e statistiche più chiari.', 'feature', '2026-04-25 10:00:00+02'),
('Raggruppamento attività per disciplina nel canvas', 'Nel canvas progetto le attività sono raggruppabili per disciplina, con totali per gruppo, ordinamento e collapse persistente.', 'feature', '2026-04-27 10:00:00+02'),
('Cancellazione gruppo di attività', 'Nuovo dialog per eliminare in un colpo solo tutte le attività di un gruppo/disciplina, con conferma esplicita.', 'improvement', '2026-04-27 11:00:00+02'),
('Popover "Assegna" più affidabile', 'Il popover di assegnazione attività ora mostra correttamente tutti gli utenti, inclusi quelli pianificati dal calendario o con ore già confermate. Risolto il caso dell''etichetta gialla mancante su progetti grandi (paginazione oltre i 1.000 record di tracking).', 'bugfix', '2026-04-29 10:00:00+02'),
('Protezione assegnazioni implicite', 'Gli utenti con eventi pianificati o ore confermate non si possono più rimuovere accidentalmente dal popover: checkbox bloccata, icona 📅 e badge "Fuso" per i non-membri del team.', 'improvement', '2026-04-29 11:00:00+02');