// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyxqldvvvjaqhramuknc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5eHFsZHZ2dmphcWhyYW11a25jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODE3ODYsImV4cCI6MjA3MjQ1Nzc4Nn0.EAU0nYt9XH8Sbuw6edd710I-NH0ZlngLIYzu5r_MhiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});