// This file is automatically generated. Do not edit it directly.
// ECCEZIONE: l'URL e la chiave ora si leggono dalle variabili d'ambiente, con
// fallback ai valori di produzione. Serve a poter lavorare in locale contro un
// progetto di staging senza toccare i dati veri: basta un .env.local.
// Se Lovable rigenera questo file, va riapplicata questa lettura da env.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://dmwyqyqaseyuybqfawvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtd3lxeXFhc2V5dXlicWZhd3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MzEyMDIsImV4cCI6MjA3NTUwNzIwMn0.YLKPhjU9h5NEq4IPrzXcfcdkzF_j8WaUTgeRCA9khh8";

// In sviluppo è utile sapere subito contro quale progetto si sta lavorando:
// scambiare staging e produzione senza accorgersene è il tipo di errore che si
// paga sui dati veri.
if (import.meta.env.DEV) {
  const ref = SUPABASE_URL.replace('https://', '').split('.')[0];
  console.info(`[supabase] progetto: ${ref}${ref === 'dmwyqyqaseyuybqfawvk' ? ' (PRODUZIONE)' : ' (staging)'}`);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
